// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQgRJrk0ihf_rO7IWdqaUyoScKJqRImg',
    appId: '1:751609463263:android:8711e4c15db77158f4c46a',
    messagingSenderId: '751609463263',
    projectId: 'instagram-clone-vandad-ba568',
    storageBucket: 'instagram-clone-vandad-ba568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzH9a2kJU5PKJ2yh2qMLXCfo0TMsL8QJU',
    appId: '1:751609463263:ios:1cd33537dd26ace7f4c46a',
    messagingSenderId: '751609463263',
    projectId: 'instagram-clone-vandad-ba568',
    storageBucket: 'instagram-clone-vandad-ba568.appspot.com',
    iosClientId: '751609463263-7m3211eomfejvc0rtakou1sb1gh5ja5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneVandadYt',
  );
}
